<a href="https://colab.research.google.com/github/kartik2627/py.torch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.3
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.6.0
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.14.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bi

In [3]:
import torch
import numpy as np


In [4]:
import random

In [5]:
my_list = [[1,2,3,4],[5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [6]:
np1=np.random.rand(3,4)
np1

array([[0.03359776, 0.82568691, 0.9578712 , 0.53034199],
       [0.74227929, 0.18528572, 0.35130857, 0.29701399],
       [0.31652642, 0.30990494, 0.59713906, 0.65592231]])

In [7]:
tensor_1 =torch.randn(3,4)
tensor_1

tensor([[-1.6900, -0.6488, -0.0371, -0.7941],
        [ 0.9320,  0.1998,  0.1045,  0.7454],
        [-0.6945, -0.8226, -1.0330,  0.5256]])

In [8]:
tensor_2 =torch.randn(2,3,4)
tensor_2


tensor([[[-0.3102,  0.5166, -1.6382, -0.8433],
         [ 0.3925,  0.4083, -1.0513,  1.5539],
         [-0.2214,  0.0789,  0.2855,  0.0691]],

        [[ 1.2181, -0.0182,  0.1456, -0.2914],
         [ 0.8101,  0.4253, -0.0390,  1.1609],
         [ 0.5124,  0.9434, -0.2911,  0.5956]]])

In [9]:
my_torch =torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#reshape and view

In [11]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch_1 = torch.arange(10)
my_torch_1 = my_torch_1.reshape(2,-1)
my_torch_1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
my_torch_2 = torch.arange(15)
my_torch_2 = my_torch_2.reshape(3,-1)
my_torch_2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [14]:
my_torch_3 = torch.arange(10)
my_torch_3 = my_torch_3.view(2,5)
my_torch_3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# building neural network using py torch

In [15]:
import torch
import torch.nn as nn
import torch.nn.functional as F

Creating the model class


In [16]:
class Model(nn.Module):
    # Define a neural network model with two hidden layers
    # in_features: Number of input features (default is 4 for flower features)
    # h1: Number of neurons in the first hidden layer (default is 8)
    # h2: Number of neurons in the second hidden layer (default is 9)
    # output_features: Number of output features (default is 3)
    def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
        super(Model, self).__init__()
        # Define the first fully connected (linear) layer with in_features input features and h1 output features
        self.fc1 = nn.Linear(in_features, h1)
        # Define the second fully connected (linear) layer with h1 input features and h2 output features
        self.fc2 = nn.Linear(h1, h2)
        # Define the output fully connected (linear) layer with h2 input features and out_features output features
        self.out = nn.Linear(h2, out_features)
    # Define the forward pass of the neural network
    def forward(self, x):
        # Pass the input tensor x through the first linear layer and apply the ReLU activation function
        x = F.relu(self.fc1(x))
        # Pass the output of the first hidden layer through the second linear layer and apply the ReLU activation function
        x = F.relu(self.fc2(x))
        # Pass the output of the second hidden layer through the output linear layer
        x = self.out(x)
        return x

Creating random NUMBER PICK THE RANDOM NUMBER FOR THE RANDOMIZATION:
This comment explains that the random seed is set to 32 using torch.manual_seed(32) to ensure reproducibility of the results. Then, an instance of the Model class is created and assigned to the variable model.


In [18]:
# Set the random seed for reproducibility

torch.manual_seed(32)

# Create an instance of the Model class
model = Model()

In [19]:
import pandas as pd
import matplotlib.pyplot as plt


In [20]:
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
my_def =  pd.read_csv(url)
my_def

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

# data set cleaning



In [37]:
my_def['Iris-setosa'] = my_def['Iris-setosa'].replace('Iris-setosa',0.0)
my_def['Iris-setosa'] = my_def['Iris-setosa'].replace('Iris-versicolor',1.0)
my_def['Iris-setosa'] = my_def['Iris-setosa'].replace('Iris-virginica',2.0)

# Train and Test the data


In [38]:
X = my_def.drop('Iris-setosa',axis=1)
y = my_def['Iris-setosa']

In [39]:
X= X.values
y= y.values

In [40]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=32)

In [45]:
x_train

array([[5.5, 2.4, 3.8, 1.1],
       [5.1, 3.4, 1.5, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [6.7, 3.3, 5.7, 2.5],
       [5.7, 2.8, 4.1, 1.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [6.3, 2.5, 5. , 1.9],
       [6. , 3. , 4.8, 1.8],
       [6.2, 2.9, 4.3, 1.3],
       [5.4, 3.9, 1.3, 0.4],
       [6.3, 2.9, 5.6, 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [6.8, 3.2, 5.9, 2.3],
       [4.6, 3.4, 1.4, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6.4, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.6, 2.9, 3.6, 1.3],
       [7. , 3.2, 4.7, 1.4],
       [6.1, 2.8, 4.7, 1.2],
       [5.8, 2.6, 4. , 1.2],
       [4.7, 3.2, 1.6, 0.2],
       [7.3, 2.9, 6.3, 1.8],
       [6.6, 2.9, 4.6, 1.3],
       [4.4, 3. , 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.7, 1.5, 0.4],
       [6.3, 2.3, 4.4, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [6.1, 3. , 4.9, 1.8],
       [5.6, 3. , 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [6.9, 3

In [46]:
x_train=torch.FloatTensor(x_train)
x_test=torch.FloatTensor(x_test)

In [49]:
# Convert y_train and y_test to tensors of type LongTensor
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)


In [50]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.01)

In [52]:
model.parameters

<bound method Module.parameters of Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)>

In [53]:
epoch = 100
losses= []
for i in range(epoch):
  y_pred = model.forward(x_train)

  loss = criterion(y_pred,y_train)
  losses.append(loss.detach().numpy())

  if i % 10 ==0:
    print(f"Epoch : {i} and loss : {loss}")
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


Epoch : 0 and loss : 1.1708258390426636
Epoch : 10 and loss : 1.1331408023834229
Epoch : 20 and loss : 1.1034339666366577
Epoch : 30 and loss : 1.07341730594635
Epoch : 40 and loss : 1.0490567684173584
Epoch : 50 and loss : 1.0299005508422852
Epoch : 60 and loss : 1.0146011114120483
Epoch : 70 and loss : 1.0010042190551758
Epoch : 80 and loss : 0.9892016649246216
Epoch : 90 and loss : 0.9762516021728516


In [54]:
with torch.no_grad():
  #basically stopping back propogation
  y_eval = model.forward(x_test)
  loss = criterion(y_eval,y_test)


In [55]:
loss

tensor(0.9861)

In [59]:
correct = 0
with  torch.no_grad():
  for i , data in enumerate(x_test):
    y_val = model.forward(data)
    print(f"{i+1} {str(y_val)} \t {y_test[i]} \t {y_val.argmax().item()}")

    if y_val.argmax().item() == y_test[i]:
      correct +=1
print(f"{correct}")

1 tensor([-0.4688,  0.4408,  0.4863]) 	 1 	 2
2 tensor([-0.1105,  0.0751,  0.1665]) 	 0 	 2
3 tensor([-0.0578,  0.0346,  0.1271]) 	 0 	 2
4 tensor([-0.3420,  0.3270,  0.3457]) 	 1 	 2
5 tensor([-0.7642,  0.6086,  0.6716]) 	 2 	 2
6 tensor([-0.6498,  0.5306,  0.5670]) 	 2 	 2
7 tensor([-0.0459,  0.0438,  0.1386]) 	 0 	 2
8 tensor([-0.0624,  0.0295,  0.1180]) 	 0 	 2
9 tensor([-0.5164,  0.4703,  0.5207]) 	 1 	 2
10 tensor([ 0.0097, -0.0210,  0.0369]) 	 0 	 2
11 tensor([-0.5650,  0.4976,  0.5438]) 	 1 	 2
12 tensor([-0.5808,  0.5177,  0.5572]) 	 2 	 2
13 tensor([-0.4424,  0.4092,  0.4455]) 	 1 	 2
14 tensor([-0.5837,  0.4889,  0.5167]) 	 1 	 2
15 tensor([-0.5913,  0.5058,  0.5455]) 	 2 	 2
16 tensor([-0.6017,  0.4835,  0.5069]) 	 2 	 2
17 tensor([-0.4109,  0.3989,  0.4348]) 	 1 	 2
18 tensor([-0.6012,  0.5275,  0.5727]) 	 2 	 2
19 tensor([-0.4759,  0.4373,  0.4721]) 	 1 	 2
20 tensor([-0.0390,  0.0291,  0.1163]) 	 0 	 2
21 tensor([-0.0898,  0.0592,  0.1407]) 	 0 	 2
22 tensor([-0.6761,  0